# pytest.ini
[pytest]
pythonpath = .
markers =
    gtfsDownloadAndExtract: marks handle GTFS static files download and extract
    gtfsProcess: marks process GTFS text files
    dbConnection: marks connect to MongoDB
    vectorsearch: marks vector search tests
    performance: marks performance benchmark tests
    gtfsRealtime: marks GTFS realtime feed updates
filterwarnings =
    ignore::DeprecationWarning